title: The Javascript coding dojo
tagline: Learn Javascript the fun way
description: What will we be learning?

- Prototypes - objects, classes and more!
- 'this' usage - bind, call, apply... THIS is the time to learn.
- Functional programming - map, filter, reduce, side effects?
- ES6/ES7 - Let's destructure the dojo!
- CSS good practices.
